# Generated by Django 2.2.13 on 2021-01-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='URL_Imagine',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
